module Sage
  class Generator
    TYPE_MAPPING = {
      Integer => "number",
      String => "string",
      TrueClass => "boolean",
      FalseClass => "boolean",
      Float => "number",
      Array => "any[]",
      Hash => "Record<string, any>"
    }

    def initialize(app_class)
      @app_class = app_class
    end

    def generate_dts
      lines = []
      lines << "// This file is auto-generated by Sage. Do not edit manually."
      lines << "export interface RpcClient {"
      
      @app_class.mounted_resources.each do |path, resource_class|
        next if resource_class.rpcs.empty?

        # Remove leading slash for property name
        prop_name = path.sub(/^\//, "")
        # If mounted at root, use "root" or skip? 
        # For now, let's assume RPCs are always namespaced or we use "root"
        prop_name = "root" if prop_name.empty?
        
        lines << "  #{prop_name}: {"
        
        resource_class.rpcs.each do |name, meta|
          params = meta[:params].map { |k, v| "#{k}: #{to_ts_type(v)}" }.join(", ")
          # Return type is any for now, but could be improved
          lines << "    #{name}(params: { #{params} }): Promise<any>;"
        end
        
        lines << "  };"
      end

      lines << "}"
      lines << "export const rpc: RpcClient;"
      lines.join("\n")
    end

    def generate_client
      interface_def = generate_dts.sub("export const rpc: RpcClient;", "")

      <<~TS
        // This file is auto-generated by Sage. Do not edit manually.
        
        #{interface_def}

        const createProxy = (path: string = ""): any => {
          return new Proxy(() => {}, {
            get: (_target, prop) => {
              const newPath = path ? \`\${path}/\${String(prop)}\` : String(prop);
              return createProxy(newPath);
            },
            apply: (_target, _thisArg, args) => {
              // Send POST request to the path
              return fetch("/" + path, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(args[0] || {})
              }).then(res => {
                if (!res.ok) throw new Error(\`RPC Error: \${res.statusText}\`);
                return res.json();
              });
            }
          });
        };

        export const rpc = createProxy() as RpcClient;
      TS
    end

    private

    def to_ts_type(ruby_type)
      TYPE_MAPPING[ruby_type] || "any"
    end
  end
end
