name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Which package is this related to?
      options:
        - Sage (Backend Framework)
        - Salvia (View Engine)
        - Both / Core Architecture
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
