// This file is auto-generated by Sage. Do not edit manually.
import { rpc as rpcRequest } from "./adapter/client.ts";

export interface RpcClient {
  home: {
    hello(params: { name: string }): Promise<any>;
  };

}

export const rpc = new Proxy({} as RpcClient, {
  get: (_, resource) => {
    return new Proxy({}, {
      get: (_, action) => async (params = {}) => {
        return await rpcRequest(String(resource), String(action), params);
      }
    });
  }
});
