require_relative "config/environment"
require "active_record"

namespace :db do
  desc "データベースを作成"
  task :create do
    Salvia::Database.create!
  end

  desc "データベースを削除"
  task :drop do
    Salvia::Database.drop!
  end

  desc "マイグレーションを実行"
  task :migrate do
    Salvia::Database.migrate!
  end

  desc "直前のマイグレーションをロールバック"
  task :rollback do
    Salvia::Database.rollback!
  end

  desc "データベースの作成とマイグレーション"
  task :setup => [:create, :migrate]
end
