// This file is auto-generated by Sage. Do not edit manually.

// This file is auto-generated by Sage. Do not edit manually.
export interface RpcClient {
  todos: {
    stats(params: {  }): Promise<any>;
  };
}


const createProxy = (path: string = ""): any => {
  return new Proxy(() => {}, {
    get: (_target, prop) => {
      const newPath = path ? `${path}/${String(prop)}` : String(prop);
      return createProxy(newPath);
    },
    apply: (_target, _thisArg, args) => {
      // Send POST request to the path
      return fetch("/" + path, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(args[0] || {})
      }).then(res => {
        if (!res.ok) throw new Error(`RPC Error: ${res.statusText}`);
        return res.json();
      });
    }
  });
};

export const rpc = createProxy() as RpcClient;
